#!/bin/bash
#
# Loaded for each terminal and sourced for login shells by ~/.bash_profile.
#
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Set the dotfile plugins to load. These correspond to files in
# $DOTFILES/plugins
#
# shellcheck disable=SC2034
export DOTFILE_PLUGINS=(
)

#
# Find out where the dotfiles repo is on disk by following the .bashrc link.
# This assumes the dotfiles `install' script has been run which makes the .bashrc
# link.
#
dotfiles_load() {
    if [ -L ~/.bashrc ]; then
        local bashrc_location
        bashrc_location=$(readlink -f ~/.bashrc)
        local dotfiles_dir=${bashrc_location%/rcs/bashrc}
        source "$dotfiles_dir/load.sh"
    fi
}
dotfiles_load
